[package]
name = "redis-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
paste = "1.0.11"
priority-queue = { version = "1.3.1", features = ["serde"] }
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
